### PR TITLE
Fix Issue/1030

### LINKED ISSUE #1030: Conflict between LifterLMS Quizzes and Starter Templates plugin
### Reproduction Steps

Install LifterLMS and Starter Templates (https://wordpress.org/plugins/astra-sites/)
Go into the Course Builder and add a quiz.

### Expected Behavior

The quiz in the Course Build should load to allow you to edit the settings.

### Actual Behavior

The spinning wheel of death keeps loading and loading so you can't edit the settings.

### Error Messages / Logs

JS error:

```
Uncaught TypeError: wp.editor.remove is not a function
    at i.render_editor (SettingsFields.js:199)
    at i.<anonymous> (SettingsFields.js:180)
    at underscore.min.js?ver=1.8.3:1
    at Function.v.each.v.forEach (underscore.min.js?ver=1.8.3:1)
    at i.render (SettingsFields.js:179)
    at i.render_subview (_Subview.js:174)
    at i.render (Quiz.js:143)
    at i.add_new_quiz (Quiz.js:251)
    at HTMLElement.dispatch (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.3.2:3)
    at HTMLElement.r.handle (load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.3.2:3)

```

HS tickets: HS-112672, HS-112814, HS-112845, HS-113000

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

In the course builder, replaces references to `wp.editor` with a helper method (`_.getEditor()`). The helper method retrieves `wp.oldEditor` (introduced in WordPress 5.0 I suppose to "resolve" naming conflicts with the `@wordpress/editor` module). If `wp.oldEditor` is not found it will attempt to use the "old" (confusing) `wp.editor` reference, but only if it's actually the TinyMCE editor and not the module version. Sigh.

Fixes #1030 

## How has this been tested?

Tested this manually.

It resolves the issue in #1030. With Astra Sites disabled it still works.

Ideally this should work on Wordpress 4.9 and lower but I didn't physically setup a 4.9 installation to test that.

## Types of changes

This is a bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo could you have a look through the update and let me know if you see any issues here please

File: assets/js/builder/main.js [hunk 1]
```diff
@@ -2,7 +2,8 @@
  * LifterLMS JS Builder App Bootstrap
  *
  * @since 3.16.0
- * @version 3.30.1
+ * @since [version] Addid `_.getEditor()` helper.
```
Comment (eri-trabiccolo) [inline assets/js/builder/main.js]:
```suggestion
 * @since [version] Added `_.getEditor()` helper.
```

File: assets/js/builder/Views/SettingsFields.js [hunk 2]
```diff
@@ -187,16 +189,24 @@ define( [], function() {
 		/**
 		 * Renders an editor field
 		 *
-		 * @param    obj   field  field data object
-		 * @return   void
-		 * @since    3.17.1
-		 * @version  3.17.1
+		 * @since  3.17.1
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/SettingsFields.js]:
```suggestion
		 * @since 3.17.1
```

File: assets/js/builder/Views/_Editable.js [hunk 3]
```diff
@@ -1,14 +1,16 @@
...
+ *
  * Use with a Model's View
  * Allows editing model.title field via .llms-editable-title elements
  *
  * @package LifterLMS/Scripts
  *
- * @since    3.16.0
- * @version  3.25.4
+ * @since  3.16.0
+ * @since  3.25.4 Unknown
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/_Editable.js]:
```suggestion
 * @since 3.16.0
 * @since 3.25.4 Unknown
```

File: assets/js/builder/Views/_Editable.js [hunk 4]
```diff
@@ -605,13 +610,17 @@ define( [], function() {
...
-		 * @param    obj   editor  wp.editor instance
-		 * @return   void
-		 * @since    3.16.0
-		 * @version  3.17.1
+		 * Updates UI if a label is present.
+		 *
+		 * Binds a change event to ensure editor changes are saved to the model.
+		 *
+		 * @since 3.16.0
+		 * @since 3.17.1 Uknown
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/_Editable.js]:
```suggestion
		 * @since 3.17.1 Uknown.
```

File: assets/js/builder/Views/_Editable.js [hunk 5]
```diff
@@ -605,13 +610,17 @@ define( [], function() {
...
+		 * @since [version] Replace references to `wp.editor` with `_.getEditor()` helper.
+		 *
+		 * @param  {Object} editor TinyMCE Editor instance.
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/_Editable.js]:
```suggestion
		 * @param {Object} editor TinyMCE Editor instance.
```

File: assets/js/builder/Views/_Editable.js [hunk 6]
```diff
@@ -544,19 +546,22 @@ define( [], function() {
...
-		 * @param    string   id        CSS ID of the editor (don't include #)
-		 * @param    obj      settings  optional object of settings to pass to wp.editor.initialize()
-		 * @return   void
-		 * @since    3.16.0
-		 * @version  3.16.0
+		 * @since 3.16.0
+		 * @since [version] Replace reference to `wp.editor` with `_.getEditor()` helper.
+		 *
+		 * @param  {String} id        CSS ID of the editor (don't include #).
+		 * @param  {Object} settings  Optional object of settings to pass to wp.oldEditor.initialize().
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/_Editable.js]:
```suggestion
		 * @param {String} id        CSS ID of the editor (don't include #).
		 * @param {Object} settings  Optional object of settings to pass to wp.oldEditor.initialize().
```

File: assets/js/builder/Views/_Editable.js [hunk 7]
```diff
@@ -544,19 +546,22 @@ define( [], function() {
...
+		 * @return {Void}
 		 */
 		init_editor: function( id, settings ) {
 
 			settings = settings || {};
 
-			wp.editor.remove( id );
+			var editor   = _.getEditor();
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/_Editable.js]:
```suggestion
			var editor = _.getEditor();
```

File: assets/js/builder/main.js [hunk 8]
```diff
@@ -94,6 +95,39 @@ require( [
...
 
+			/**
+			 * Retrieve the wp.editor instance.
+			 *
+			 * Uses `wp.oldEditor` (when available) which was added in WordPress 5.0.
+			 *
+			 * Falls back to `wp.editor()` which will usually be the same as `wp.oldEditor` unless
+			 * the `@wordpress/editor` module has been loaded by another plugin or a theme.
+			 *
+			 * @since  [version]
```
Comment (eri-trabiccolo) [inline assets/js/builder/main.js]:
```suggestion
			 * @since [version]
```
